### ISSUE TITLE
Please upload to curseforge

### ISSUE THREAD

**Issue by LordMZTE** [ferreusveritas/MagicCrackerFactory#1]
why dont you put this on curseforge? ittl make it so much easier for everyone to play with this mod

**Comment by ferreusveritas** [comment]
It's not ready for general use in my opinion.  As soon as I post it I'm going to be eaten alive by bug reports and feature requests. I'm just not ready to deal with it right now.  Those who want to use this can compile from source.
Are you interested in using the mod?

**Comment by LordMZTE** [comment]
yeah i am

> 
> 
> It's not ready for general use in my opinion. As soon as I post it I'm going to be eaten alive by bug reports and feature requests. I'm just not ready to deal with it right now. Those who want to use this can compile from source.
> Are you interested in using the mod?

,

**Comment by ferreusveritas** [comment]
Uploaded to curseforge some time ago.
